### ISSUE TITLE
Need information on how to register on Laravel 11.

### ISSUE THREAD

**Issue by ChaosWebDev** [umer6418129/Lara-Repo#1]
Hello,
config/app.php doesn't have a 'providers' option anymore.

Should this be going in to app/Providers/ServiceProviders.php into the register() method?

**Comment by ChaosWebDev** [comment]
My apologies, it's now under bootstrap/providers.php

[Laravel 11 - Registering Providers](https://laravel.com/docs/11.x/providers#registering-providers)

**Comment by umer6418129** [comment]
Hi there,
Thanks for reach me out, currently we are working to make it compatible with laravel 11 it will be done with in a week.

Thanks
Regards
M.Umer Farooq.
